/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.alvincabayan.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.alvincabayan.model.MenuOrder;

public interface MenuOrderApi {

	@RequestMapping(value = "/menuorder", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.POST)
	ResponseEntity<Void> addMenuOrder(@Valid @RequestBody MenuOrder body);

	@RequestMapping(value = "/menuorder/{idmenuorder}", produces = { "application/json" }, method = RequestMethod.DELETE)
	ResponseEntity<Void> deleteMenuOrder(Long orderId, @RequestHeader(value = "api_key", required = false) String apiKey);

	@RequestMapping(value = "/menuorder/{idmenuorder}", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<MenuOrder> getMenuOrderById(@PathVariable("orderId") Long orderId);

	@RequestMapping(value = "/menuorder", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.PUT)
	ResponseEntity<Void> updateMenuOrder(@Valid @RequestBody MenuOrder body);

	@RequestMapping(value = "/menuorder/{idmenuorder}", produces = { "application/json" }, consumes = {
			"application/x-www-form-urlencoded" }, method = RequestMethod.POST)
	ResponseEntity<Void> updateMenuOrderWithForm(@PathVariable("orderId") Long orderId,
			@RequestParam(value = "name", required = false) String name,
			@RequestParam(value = "status", required = false) String status);

}
