/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.alvincabayan.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.alvincabayan.model.MenuOrder;

public interface OrderApi {

	@RequestMapping(value = "/order", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.POST)
	ResponseEntity<Void> addOrder(@Valid @RequestBody MenuOrder body);

	@RequestMapping(value = "/order/{orderId}", produces = { "application/json" }, method = RequestMethod.DELETE)
	ResponseEntity<Void> deleteOrder(Long orderId, @RequestHeader(value = "api_key", required = false) String apiKey);

	@RequestMapping(value = "/order/{orderId}", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<MenuOrder> getOrderById(@PathVariable("orderId") Long orderId);

	@RequestMapping(value = "/order", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.PUT)
	ResponseEntity<Void> updateOrder(@Valid @RequestBody MenuOrder body);

	@RequestMapping(value = "/order/{orderId}", produces = { "application/json" }, consumes = {
			"application/x-www-form-urlencoded" }, method = RequestMethod.POST)
	ResponseEntity<Void> updateOrderWithForm(@PathVariable("orderId") Long orderId,
			@RequestParam(value = "name", required = false) String name,
			@RequestParam(value = "status", required = false) String status);

}
